Basic VR Browser Support
nanome-ai/nanome-lib pull request #217
Opened 2021-08-07 01:34 UTC by EthanVanderHorn

2021-08-07 03:52 UTC, mjrosengrant requested changes

2021-08-07 03:52 UTC, mjrosengrant commented on nanome/api/plugin_instance.py
> +    def open_url(self, url, desktopBrowser=False):
```suggestion
    def open_url(self, url, desktop_browser=False):
```

2021-08-07 03:52 UTC, mjrosengrant commented on nanome/api/plugin_instance.py
> +        self._network._send(_Messages.open_url, (url, desktopBrowser), False)
```suggestion
        self._network._send(_Messages.open_url, (url, desktop_browser), False)
```

2021-08-09 18:49 UTC, Ramjii approved these changes
Besides what Mike suggested, this looks good

2021-08-18 22:27 UTC, ajm13 approved these changes

2021-08-18 22:30 UTC, mjrosengrant approved these changes

2021-08-19 00:20 UTC, merged